name: ChestCommands
main: com.gmail.filoghost.chestcommands.ChestCommands
version: 3.1.1
softdepend: [Vault, BarAPI, PlayerPoints]

commands:
   chestcommands:
      description: Main command for ChestCommands.
      usage: /<command> (Startup error)
      aliases: [cc]

permissions:
  chestcommands.economy.bypass:
    description: Bypass command costs.
    default: false